### ISSUE TITLE
http://dexterjs.com/ is down

### ISSUE THREAD

**Issue by vladikoff** [leobalter/DexterJS#24]

**Comment by leobalter** [comment]
The site is down because I've to cancel almost all my subscriptions as I'm moving to another country and I'll need to cancel my former credit card accs.

Currently the documentation is [here](https://github.com/leobalter/DexterJS/tree/master/docs) and it can be turned into a html presentation using `grunt mdoc`

**Comment by vladikoff** [comment]
@leobalter Thanks!
